/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dev.MusicBands;

import com.dev.MusicBands.entity.Song;
import com.dev.MusicBands.entity.Statistics;
import com.dev.MusicBands.model.SongModel;
import com.dev.MusicBands.service.AdminService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import org.springframework.context.annotation.Import;
import org.springframework.stereotype.Component;

/**
 *
 * @author Root
 */
@Component
@Import(value = AdminService.class)
public class PlayFrame extends javax.swing.JFrame {

    AdminService service;
    AdminFrame adminFrame;
    List<Song> list = new ArrayList<>();
    SongModel model = new SongModel(list);
    Song song;
  
    

    /**
     * Creates new form PlayFrame
     */
    public PlayFrame(AdminService service) {
        this.service = service;
        initComponents();
        initUI();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btPlay = new javax.swing.JButton();
        btStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSong = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Назва пісні, альбому чи групи");
        jPanel1.add(jLabel1);

        search.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search.setMinimumSize(new java.awt.Dimension(200, 22));
        search.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel1.add(search);

        btSearch.setText("Пошук");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btSearch);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btPlay.setText("Play");
        btPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });
        jPanel2.add(btPlay);

        btStop.setText("Stop");
        btStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStopActionPerformed(evt);
            }
        });
        jPanel2.add(btStop);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tSong.setModel(model);
        jScrollPane1.setViewportView(tSong);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:
        if (search.getText().isEmpty()) {
            return;
        }
        String str = "%" + search.getText() + "%";
        System.out.println(str);
        list = service.searchSong(str);
        System.out.println(list.size());
        model.update(list);
        model.fireTableDataChanged();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                tSong.repaint();
            }
        });

    }//GEN-LAST:event_btSearchActionPerformed

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlayActionPerformed
        // TODO add your handling code here:
        //Statistics stat = tSong.getS
        int row = tSong.getSelectedRow();
        if (row >= 0) {
            Song song = (Song) tSong.getModel().getValueAt(row, 100);
            Statistics st = song.getStatistics();
            int i = st.getCounter();
            i++;
            st.setCounter(i);
            st = service.saveStatisics(st);
            JOptionPane.showMessageDialog(null,String.format("play song %s",song.getName()));
            
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    tSong.repaint();
                  
                }
            });
        }

    }//GEN-LAST:event_btPlayActionPerformed

    private void btStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStopActionPerformed

    }//GEN-LAST:event_btStopActionPerformed

    private void initUI() {
        JMenuBar menuBar = new JMenuBar();
        JMenu adminMenu = new JMenu("Адмінка");
        JMenuItem adminItem = new JMenuItem("Групи, моделі, пісні");
        adminItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (adminFrame == null) {
                    adminFrame = new AdminFrame(service);
                }
                adminFrame.setVisible(true);

            }
        });
        adminMenu.add(adminItem);
        menuBar.add(adminMenu);
        setJMenuBar(menuBar);
        setTitle("App music");
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPlay;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTable tSong;
    // End of variables declaration//GEN-END:variables

   
}
